---
name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
    
      - name: Build Docker image
        run: |
          docker build \
            -t eu.gcr.io/real-estate-classifieds/actions-test/test:${{ github.sha }} \
            .

      - name: Login to Google Cloud
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        run: |
          echo "$GCLOUD_AUTH" | base64 --decode > ${HOME}/gcloud.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud.json
          gcloud auth configure-docker
          rm ${HOME}/gcloud.json

      - uses: Pararius/gcr-deploy@v0.3
        with:
          host: eu.gcr.io
          project: real-estate-classifieds
          image: actions-test/test
          tag: ${{ github.sha }}
