---
name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
    
      - name: Build Docker image
        run: |
          docker build \
            -t eu.gcr.io/real-estate-classifieds/actions-test/test:${GITHUB_SHA::8} \
            .
    
      - uses: Pararius/gcr-deploy@v0.1
        with:
          host: eu.gcr.io
          project: real-estate-classifieds
          image: test
          tag: ${{ github.sha }}
          tag-as-latest: true
